### ISSUE TITLE
Implement torchIO and the necessary data augmentation strategies in ivadomed

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_ms_mp2rage#16]
Context: https://github.com/ivadomed/model_seg_ms_mp2rage/pull/11#issuecomment-992718212

The data augmentations we would like to implement to parallelize the the two pipelines (i.e. custom script mentioned in the context above and ivadomed) in the hopes of achieving better performance with ivadomed are:
- [x] Random flipping in all axes
- [x] Random gamma contrast
- [x] Random bias field
- [x] Random blur

**Comment by uzaymacar** [comment]
Random flipping in all axes now works in ivadomed with a bug fix introduced with the already merged PR [#1013](https://github.com/ivadomed/ivadomed/pull/1013). Random gamma contrast augmentation is now implemented in ivadomed with the ready-to-be-reviewed PR [#1015](https://github.com/ivadomed/ivadomed/pull/1015). The task list above is updated accordingly.

**Comment by uzaymacar** [comment]
Random bias field augmentation is now implemented in ivadomed with the ready-to-be-reviewed PR [#1033](https://github.com/ivadomed/ivadomed/pull/1033). The task list above is updated accordingly.

**Comment by uzaymacar** [comment]
Random blur augmentation is now implemented in ivadomed with reviewed and merged PR [#1034](https://github.com/ivadomed/ivadomed/pull/1034).

With this, I am closing this issue as all four augmentations has been implemented in ivadomed.
