### ISSUE TITLE
Change name of repository to `model_seg_lesion_mp2rage`

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_ms_mp2rage#25]
To be consistent with the sister repository: https://github.com/ivadomed/model_seg_sc_mp2rage

**Comment by uzaymacar** [comment]
Closing this issue as discussed in the previous meeting (i.e. no need to change the name of repository) because
* we decided to have a single repository for both models and
* the `lesion` and `sc` separation is therefore no longer necessary: we can stick to `ms`.
