### ISSUE TITLE
Use of `"target_suffix": ["_lesion-manual"]` leads to multiple targets during training and testing

### ISSUE THREAD

**Issue by uzaymacar** [ivadomed/model_seg_ms_mp2rage#41]
As discussed in more detail in https://github.com/ivadomed/ivadomed/issues/1055, I recently discovered that the use `_lesion-manual` as the target suffix leads to `ivadomed` using all derivatives which have the `_lesion-manual` string in it (e.g. `_lesion-manual.nii.gz`, `_lesion-manual-majvote`, `_lesion-manual2.nii.gz`, etc.).

This creates inconsistencies in training and testing. For example, running `ivadomed --test -c config/test_on_rater1.json` yields different results in each run as a different GT is selected from the derivatives that contain the `_lesion-manual` string.

As mentioned in the ivadomed issue linked above, a quick fix for now is to update the `"target_suffix"` to include the `.nii.gz` file extension. This is because the target suffix string `_lesion-manual.nii.gz` breaks the overlap between the filenames `_lesion-manual.nii.gz` and `_lesion-manual2.nii.gz` (and also the other derivatives).

The next steps are to:
- [x] Update all config files to include the `.nii.gz` extension in the `"target_suffix"` key (will link a PR soon)
- [x] Re-train and re-test lesion segmentation (note: no need to do this for SC segmentation as we have one label for this task)

**Comment by jcohenadad** [comment]
Not needed anymore as we are now using a single-rater segmentation (_NeuroPoly)
