### ISSUE TITLE
MS lesions masks outside the SC mask

### ISSUE THREAD

**Issue by Nilser3** [ivadomed/model_seg_ms_mp2rage#79]
# Description

139 subjects of the 180 MS subjects in the `basel-mp2rage` database have lesion segmentation pixels (lesion-manualNeuroPoly mask) that are outside the SC segmentation

Here an example:
## sub-P121
![lesion_SC](https://github.com/ivadomed/model_seg_ms_mp2rage/assets/77469192/6b8b99cc-a05c-4c12-a347-4915b81859b2)
List of subjects with this issue: ``sub-P001``, ``sub-P003``, ``sub-P004``, ``sub-P005``, ``sub-P006``, ``sub-P007``, ``sub-P010``, ``sub-P011``, ``sub-P012``, ``sub-P013``, ``sub-P014``, ``sub-P016``, ``sub-P019``, ``sub-P021``, ``sub-P022``, ``sub-P023``, ``sub-P024``, ``sub-P025``, ``sub-P026``, ``sub-P027``, ``sub-P028``, ``sub-P030``, ``sub-P031``, ``sub-P033``, ``sub-P034``, ``sub-P035``, ``sub-P036``, ``sub-P037``, ``sub-P038``, ``sub-P039``, ``sub-P040``, ``sub-P041``, ``sub-P042``, ``sub-P044``, ``sub-P045``, ``sub-P047``, ``sub-P050``, ``sub-P051``, ``sub-P053``, ``sub-P055``, ``sub-P056``, ``sub-P057``, ``sub-P058``, ``sub-P059``, ``sub-P061``, ``sub-P062``, ``sub-P063``, ``sub-P065``, ``sub-P066``, ``sub-P067``, ``sub-P068``, ``sub-P069``, ``sub-P070``, ``sub-P071``, ``sub-P072``, ``sub-P075``, ``sub-P078``, ``sub-P079``, ``sub-P082``, ``sub-P084``, ``sub-P085``, ``sub-P086``, ``sub-P087``, ``sub-P088``, ``sub-P094``, ``sub-P095``, ``sub-P096``, ``sub-P097``, ``sub-P098``, ``sub-P099``, ``sub-P100``, ``sub-P101``, ``sub-P103``, ``sub-P104``, ``sub-P106``, ``sub-P108``, ``sub-P109``, ``sub-P110``, ``sub-P111``, ``sub-P112``, ``sub-P114``, ``sub-P116``, ``sub-P117``, ``sub-P119``, ``sub-P120``, ``sub-P121``, ``sub-P122``, ``sub-P124``, ``sub-P125``, ``sub-P129``, ``sub-P130``, ``sub-P132``, ``sub-P134``, ``sub-P138``, ``sub-P139``, ``sub-P141``, ``sub-P142``, ``sub-P144``, ``sub-P145``, ``sub-P146``, ``sub-P148``, ``sub-P149``, ``sub-P151``, ``sub-P153``, ``sub-P156``, ``sub-P157``, ``sub-P160``, ``sub-P161``, ``sub-P165``, ``sub-P167``, ``sub-P169``, ``sub-P170``, ``sub-P173``, ``sub-P174``, ``sub-P175``, ``sub-P176``, ``sub-P178``, ``sub-P179``, ``sub-P180``, ``sub-P181``, ``sub-P182``, ``sub-P183``, ``sub-P185``, ``sub-P187``, ``sub-P188``, ``sub-P190``, ``sub-P191``, ``sub-P192``, ``sub-P194``, ``sub-P197``, ``sub-P199``, ``sub-P200``, ``sub-P241``, ``sub-P242``, ``sub-P243``, ``sub-P244``, ``sub-P246``, ``sub-P249``, ``sub-P250``

Maybe we should redefine the SC masks by making a union of the MS lesions and current SC masks

**Comment by jcohenadad** [comment]
@Nilser3 this issue refers to the data, not to the model-- can you please move this issue to https://github.com/neuropoly/data-management/issues and I will then comment there-- thanks!

**Comment by Nilser3** [comment]
This issue is closed, and a [new one](https://github.com/neuropoly/data-management/issues/266) is opened in the correct repo 
(the issue could not be transferred because they are different organizations `ivadomed/model_seg_ms_mp2rage`    and `neuropoly/data-managemment` )
